### ISSUE TITLE
Improve Error Messaging when deploying to an account that isn't configured for Herman use

### ISSUE THREAD

**Issue by rdbatch02** [libertymutual/herman#84]
When attempting to run an ECS Deploy against an account that doesn't have Herman settings present (missing configuration bucket and/or properties.yml), the current error messaging isn't particularly helpful to inexperienced users.

For example:

```
java.lang.RuntimeException: Error getting ECS Push Task Properties
	        at com.libertymutualgroup.herman.task.ecs.ECSPushPropertyFactory.getTaskProperties(ECSPushPropertyFactory.java:44)
	        at com.libertymutualgroup.herman.task.ecs.ECSPushPropertyFactory.getTaskProperties(ECSPushPropertyFactory.java:33)
	        at com.libertymutualgroup.herman.task.bamboo.ecs.ECSPushTask.doExecute(ECSPushTask.java:65)
	        at com.libertymutualgroup.herman.aws.AbstractDeploymentTask.execute(AbstractDeploymentTask.java:39)
	        at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$1(TaskExecutorImpl.java:315)
	        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:252)
	        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:315)
	        at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:112)
	        at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:73)
	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.executeBuildPhase(DefaultBuildAgent.java:204)
	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:176)
	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.lambda$waitAndPerformBuild$0(BuildAgentControllerImpl.java:131)
	        at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:185)
	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:125)
	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:127)
	        at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
	        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
	        at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
	        at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
	        at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.RuntimeException: Error getting Herman Configuration from properties.yml
	        at com.libertymutualgroup.herman.util.ConfigurationUtil.getHermanConfigurationAsString(ConfigurationUtil.java:48)
	        at com.libertymutualgroup.herman.task.ecs.ECSPushPropertyFactory.getTaskProperties(ECSPushPropertyFactory.java:38)
	        ... 19 more
	Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket;
```

Instead it's probably more useful if we say something to the effect of:

```
ERROR: This AWS Account is not configured for Herman! Please ensure that the appropriate configuration bucket and files are in place, or that you're using the correct AWS Account.

Account ID: 123456789
Account Alias: aws-account-alias
```

**Comment by KidPluto** [comment]
When this happened to me, I got a message like
`Stack with id of XYZ-shared does not exist`
I had defined XYZ, no idea where the "-shared" came from.

**Comment by rdbatch02** [comment]
This is probably a separate issue @KidPluto. The -shared stack is part of the cluster deploy process [](https://github.com/libertymutual/herman/blob/master/docs/Cluster_Deployment.md)
